CREATE DATABASE IF NOT EXISTS test;

CREATE TABLE IF NOT EXISTS  users(
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  timestamp TIMESTAMP
);
